# Generated by Django 2.0.6 on 2018-07-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation_Models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128)),
                ('user_in', models.CharField(max_length=256)),
                ('braggi_out', models.CharField(max_length=256)),
                ('intent', models.CharField(max_length=64)),
                ('invoked_event', models.CharField(max_length=128)),
                ('rating', models.CharField(max_length=2)),
            ],
        ),
    ]
