# Generated by Django 2.0.6 on 2018-07-15 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation_models',
            options={'ordering': ()},
        ),
    ]
