# Generated by Django 2.0.6 on 2018-07-15 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20180715_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation_models',
            options={'ordering': ('user_name',)},
        ),
    ]
