# Generated by Django 2.0.6 on 2018-07-15 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20180715_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation_models',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
