# Generated by Django 2.0.6 on 2018-07-15 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_auto_20180715_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation_models',
            name='rating',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
