# Generated by Django 2.0.6 on 2018-07-15 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_remove_conversation_models_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conversation_Models',
            new_name='Conversation',
        ),
    ]
